export const MARKETS = [
  { value: 'crypto', label: 'Crypto' },
  { value: 'forex', label: 'Forex' },
  { value: 'stocks', label: 'Stocks/Equities' },
  { value: 'synthetic', label: 'Synthetic Indices' },
];

export const DIRECTIONS = [
  { value: 'long', label: 'Long / Buy' },
  { value: 'short', label: 'Short / Sell' },
];

export const STRATEGIES =[
  "1 Minute Scalping",
  "5 Minute Scalping",
  "ADX Trend Strategy",
  "AI Trading",
  "Afternoon Fade",
  "Algorithmic Trading",
  "Anti Martingale",
  "Airdrop Farming",
  "Asian Range Breakout",
  "ATR Strategy",
  "Auction Market Theory",
  "Basket Trading",
  "Behavioral Finance Trading",
  "Beta Neutral Trading",
  "Bid Ask Scalping",
  "Bollinger Bands Reversal",
  "Bollinger Bands Strategy",
  "Break and Retest",
  "Break of Structure",
  "Buy and Hold Trend Following",
  "Calendar Spread",
  "Calendar Spread Futures",
  "Candlestick Trading",
  "Carry Trade",
  "CCI Strategy",
  "Change of Character",
  "Channel Breakout",
  "Channel Swing Trading",
  "Channel Trend Trading",
  "Chaos Theory Trading",
  "Collar Strategy",
  "Commodity Seasonality",
  "Compression Breakout",
  "Convertible Arbitrage",
  "Correlation Trading",
  "Counter Trend Trading",
  "Covered Call",
  "Credit Spread",
  "Crypto Arbitrage",
  "Dark Pool Tracking",
  "Debit Spread",
  "Dividend Strategy",
  "DOM Scalping",
  "DOM Trading",
  "Dollar Neutral Trading",
  "Donchian Channel Breakout",
  "Economic Cycle Trading",
  "Economic Data Trading",
  "Election Cycle Trading",
  "EMA Pullback",
  "Engulfing Candle Strategy",
  "Earnings Gap Strategy",
  "Earnings Momentum",
  "Earnings Swing Trading",
  "Earnings Trading",
  "ETF Arbitrage",
  "Event Driven Trading",
  "Factor Investing",
  "Fair Value Gap",
  "Fakey Setup",
  "Fade Strategy",
  "Fibonacci Retracement Swing",
  "Fibonacci Strategy",
  "Footprint Chart Trading",
  "Fractal Trading",
  "Funding Rate Arbitrage",
  "Fundamental Position Trading",
  "Gamma Scalping",
  "Gamma Trading",
  "Gap and Go",
  "Gap Trading",
  "Grid Trading",
  "Growth Investing",
  "Heikin Ashi Trend Trading",
  "Hedging",
  "High Frequency Trading",
  "Iceberg Detection",
  "Iceberg Orders",
  "Ichimoku Trend Trading",
  "Index Arbitrage",
  "Inflation Trading",
  "Inside Bar Breakout",
  "Interest Rate Trading",
  "Intraday Breakout",
  "Intraday Reversal",
  "Intraday Support Resistance",
  "Intraday Trend Trading",
  "Iron Butterfly",
  "Iron Condor",
  "Keltner Channel Strategy",
  "Latency Arbitrage",
  "Liquidity Based Trading",
  "Liquidity Grab Scalping",
  "Liquidity Hunt",
  "Liquidity Sweep",
  "Long Short Equity",
  "Long Term Breakout",
  "Long Volatility",
  "London Breakout",
  "MACD Strategy",
  "MACD Swing Trading",
  "MACD Trend Strategy",
  "Machine Learning Trading",
  "Macro Trading",
  "Macro Trend Trading",
  "Market Neutral Algorithm",
  "Market Profile Trading",
  "Market Structure Trading",
  "Martingale",
  "Mean Reversion Trading",
  "Merger Arbitrage",
  "Mitigation Block",
  "Momentum Trading",
  "Moving Average Crossover",
  "Moving Average Reversion",
  "Moving Average Swing Trading",
  "Neural Network Trading",
  "News Based Day Trading",
  "News Momentum Trading",
  "News Scalping",
  "News Spike Trading",
  "News Trading",
  "OBV Strategy",
  "On Chain Analysis Trading",
  "Opening Drive",
  "Opening Range Breakout",
  "Order Block Trading",
  "Order Flow Trading",
  "Pairs Trading",
  "Parabolic SAR Strategy",
  "Pennant Breakout",
  "Perpetual Futures Basis Trading",
  "Pin Bar Strategy",
  "Pivot Point Strategy",
  "Pivot Point Trading",
  "Price Acceleration Strategy",
  "Protective Put",
  "Pullback Trading",
  "Pure Arbitrage",
  "Quant Trading",
  "Range Breakout",
  "Ratio Spread",
  "Rectangle Breakout",
  "Relative Strength Strategy",
  "Relative Value Trading",
  "Reinforcement Learning Trading",
  "Reversal Day Trading",
  "RSI Momentum Breakout",
  "RSI Overbought Oversold",
  "RSI Strategy",
  "RSI Swing Strategy",
  "Sector Momentum Rotation",
  "Sector Rotation",
  "Sector Rotation Swing",
  "Seasonal Trading",
  "Secular Trend Strategy",
  "Sentiment Analysis Trading",
  "Short Volatility",
  "Small Cap Momentum",
  "Smart Beta Strategy",
  "Smart Money Concepts",
  "Spatial Arbitrage",
  "Spread Scalping",
  "Squeeze Breakout",
  "Statistical Arbitrage",
  "Statistical Mean Reversion",
  "Stochastic Strategy",
  "Straddle",
  "Strangle",
  "Support Resistance Breakout",
  "Support Resistance Flip",
  "Supply and Demand Zones",
  "Supertrend Strategy",
  "Swing Breakout",
  "Swing Pullback",
  "Tape Reading",
  "Thematic Investing",
  "Tick Scalping",
  "Trend Trading",
  "Trendline Trading",
  "Triangle Breakout",
  "Triangular Arbitrage",
  "Turtle Trading",
  "TWAP Strategy",
  "Value Investing",
  "Vega Trading",
  "VIX Trading",
  "Volatility Arbitrage",
  "Volatility Breakout",
  "Volatility Crush Trading",
  "Volume Profile Trading",
  "Volume Surge Momentum",
  "VWAP Execution",
  "VWAP Intraday",
  "VWAP Momentum Trading",
  "VWAP Reversion",
  "VWAP Scalping",
  "VWAP Strategy",
  "Weekly Trend Swing",
  "Wheel Strategy",
  "Wyckoff Method",
  "Z-Score Reversion"
]

export const inputClass = `w-full bg-gray-800 border text-blue-100 border-gray-700 rounded-lg px-4 py-3
     placeholder-gray-500 focus:outline-none focus:border-blue-500
    transition-colors text-sm`;

export  const labelClass = `text-xs text-blue-300 uppercase tracking-wider mb-1 block`;

export const COLORS = {
  win: '#4ade80',
  loss: '#f87171',
  breakeven: '#94a3b8',
  blue: '#60a5fa',
  purple: '#a78bfa',
};


export const PIE_COLORS = [COLORS.win, COLORS.loss, COLORS.breakeven];

export   const navLinks = [
    { href: "/", label: "Dashboard" },
    { href: "/analytics", label: "Analytics" },
      { href: '/import',  label: 'Import' },
    { href: "/trades/new", label: "+ Log Trade" },
  ];

